### ISSUE TITLE
MergePlane does not accept input

### ISSUE THREAD

**Issue by l00mi** [cpvrlab/ImagePlay#35]
After split plane with a vertical flip, the merge plane does not allow a connection.

https://gist.github.com/l00mi/9b9a6fc81fce4a85ac53

**Comment by mfrischknecht** [comment]
Merge plane per se works fine; the main problem is that it is only accepting grayscale images as input (which actually makes sense), whereas the flip process currently always generates RGB images (because it could theoretically get RGB input). Currently, only automatic "upward" conversions are implemented (i.e. B/W > GRAY > RGB).

The solution would therefore be to implement automatic changes to the output of various processes (i.e. if "Flip Image" gets a grayscale input, it will return grayscale output). To navigate around this issue, one can currently simply use the "Convert to Gray" process:

![screenshot from 2015-04-04 22 13 45](https://cloud.githubusercontent.com/assets/7261570/6994386/e63e0b2e-db17-11e4-8df0-32ec2441c9a0.png)
