### ISSUE TITLE
Plugin code generation failed on linux

### ISSUE THREAD

**Issue by zuf** [cpvrlab/ImagePlay#61]
Tried to generate plugin sources stub and got this errors:

```
11:06:36 Creating directory: "/home/zuf/plugin_development/XorTexture"
11:06:36 "/home/zuf/plugin_development/_template/NAME.h" not readable!
11:06:36 "/home/zuf/plugin_development/_template/NAME.pro" not readable!
11:06:36 "/home/zuf/plugin_development/_template/NAME.vcxproj" not readable!
```

All permissions to write to this deirectory is ok.

![imageplay-plugin-generator-bug](https://cloud.githubusercontent.com/assets/105518/9106904/36a4607a-3c2c-11e5-97fb-107ab95b9db7.png)

**Comment by leni536** [comment]
Same here, note that for some reason it searches the "plugin_development" directory in the current working directory. If ImagePlay is started from it's own directory then it finds the template files, but doesn't actually create the new project directory and fails to create the new project files.

**Comment by schmk2** [comment]
We are looking for QDir::currentPath() + "/plugin_development/_template/". It works with our Windows build but needs a fix for Linux/OSX.

**Comment by l00mi** [comment]
Would QDir::homePath() work for this?

**Comment by leni536** [comment]
I think the sanest method is providing an install script with a prefix option (the usual "make install" method, don't know how it works with qmake though). I think homePath doesn't help here.

**Comment by zuf** [comment]
Personally I prefer to choose directories where plugins and plugins source templates would stored.
Force user to using some hardcoded directory into their home directory doesn't very nice.

Could we add path to plugins directory to settings and ask user where to save plugin template code?

**Comment by mfrischknecht** [comment]
Since we use QSettings anyway, I would propose to use QApplication::setApplicationName() [1] and QApplication::setOrganizationName() in the main() function. This way, one can default-construct a QSettings-Object anywhere (eliminating the need for MainWindow::_settings) and use the path of the settings file that Qt chooses by default, which is quite sensible.
On linux, it should lie somewhere in ~/.config, and on Windows in %appdata% (I don't know the location for BSD-Like systems like OSX...).

Note: For this to work, QSettings::setDefaultFormat() [2] has to be set to a file type (e.g. QSettings::IniFormat) to be consistent between platforms (the default for Windows-Systems writes and reads Registry keys, which doesn't yield the desired file name).


[1]: http://doc.qt.io/qt-4.8/qcoreapplication.html#applicationName-prop
[2]: http://doc.qt.io/qt-5/qsettings.html#setDefaultFormat
