### ISSUE TITLE
Change packaging for UNIX-like platforms

### ISSUE THREAD

**Issue by mfrischknecht** [cpvrlab/ImagePlay#64]
Fabian-z from the Arch Linux forums created an AUR-PKGBUILD for ImagePlay and notes some valid concerns: https://bbs.archlinux.org/viewtopic.php?pid=1550982#p1550982

Basically, the idea of shipping icons and such in the application directory may be valid for Windows systems, but is generally not a best practice on UNIX-like systems. To integrate better into those, it would be recommendable to integrate all assets of the main application into the binary itself (e.g. through [QResource]). This way, packagers don't have to create strange subdirectories in /opt.

This also ties in with issue #61, where the selection of the assets directory for plugins has to be changed too.

[QResource]: http://doc.qt.io/qt-4.8/qresource.html

**Comment by bobvanderlinden** [comment]
It would be alright to have the assets as separate files, as long as its location is configurable. I'm not very familiar with QMake, so I don't know how installs of applications and their assets should work.

**Comment by l00mi** [comment]
We have now added the possibility to change all paths trough [QSettings](http://doc.qt.io/qt-5/qsettings.html). Will that do for proper packaging?

**Comment by bobvanderlinden** [comment]
I have packaged 6.0.0-rc.0 for NixOS. It is not to NixOS yet, since this is still a rc, but you can find the package here: https://github.com/bobvanderlinden/nixpkgs/blob/a63e2b12242e5bad7c81545db58f0b0d9d51e6ca/pkgs/applications/graphics/imageplay/default.nix

Usually for Linux projects you'd install the software with `make install`. This typically would install executable binaries to `/usr/bin`, libraries to `/usr/lib/` and shared resources (like icons) into `/usr/share/{APPNAME}/`.
What would help other packagers is to have a make-install rule that installs all files to these appropriate directories.

KeePassX does this nicely: https://github.com/abbot/keepassx/blob/master/src/src.pro#L37-L75

Alternatively, for closed source packages and packages that do not adhere to these standards, software can be placed in `/opt/{APPNAME}/`. At the moment I have packaged imageplay this way.
I wasn't able to get everything in the standard directories, since imageplay is explicitly looking in its own application directory, like here:
https://github.com/cpvrlab/ImagePlay/blob/ecbe5a8cf042bb4aa9d9bea97d8df9f38cff0d4d/ImagePlay/src/IPProcessListTabWidget.cpp#L132

At the moment this is not a problem for me, but it would probably help other packagers and make it more likely imageplay is included in other repositories.

**Comment by schmk2** [comment]
Thank you for these tips. We will try to implement some useful install instructions in our .pro file.

**Comment by schmk2** [comment]
I have added all necessary changes to the .pro file and removed hard coded references from src.
You can now install using `make install`, see  https://github.com/cpvrlab/ImagePlay/blob/master/install.md#linux
