### ISSUE TITLE
Implement Gradient operator

### ISSUE THREAD

**Issue by LavrentyLavrov** [cpvrlab/ImagePlay#71]
Application instantly crashes when i drag arrow to the gradient operator.

**Comment by l00mi** [comment]
Aight, there seems to be a bug deeper in the alogrithm. We might put this process on hold and add it again after 6.0.0-rc.1.

**Comment by l00mi** [comment]
Make the `IPLGradientOperator` operator work.

**Comment by ladotonia** [comment]
I've got a preliminary version with the gradient operators listed.  I was not entirely sure what Cubic Spline was intended to be, so I opted to go with a bicubic interpolation and calculate the gradient based on that.

The original crasher was a bug in the constructor of an IMAGE_ORIENTED not having enough planes to support the data being inserted into it.

I also am not 100% sure how these should operate if useOpenCv is not set.  Fast gradient doesn't use OpenCV at all, where all the others do.  Sobel is an opencv function, Roberts is implemented using filter2D(), and the Bicubic interpolation only uses the matrix multiply/dot operations from OpenCV.

Here's a link to my branch with the code.  I can create a pull request once I can incorporate some feedback on dealing with the OpenCV setting.
ladotonia@32cb3afd8c3295e6d19a6c04c4ec081bb5ad0274

**Comment by schmk2** [comment]
A clarification for useOpenCv:
We originally had no opencv code, just our own implementation of algorithms. Then we added opencv and some algorithms now have 2 separate implementations. Even though opencv is almost always faster, want to leave our own implementation because it is generally more legible and thus better for learning from the source code.

The user can set in the GUI if he prefers the opencv or the custom implementation, which is then passed to you as the parameter useOpenCv.

Additionally, each IPLProcess can specify OPENCV_NONE, OPENCV_OPTIONAL or OPENCV_ONLY which is used for the GUI representation of the process.

In your case, the best way is to add in init():
setOpenCVSupport( IPLOpenCVSupport::OPENCV_ONLY );

And remove:
if( useOpenCV )

**Comment by drzraf** [comment]
Checking "Cubic Spline" simply connected to "Camera > Convert to Grey' consistently segfault.
6.1.0, OpenCV 3.1, Qt 5.9.5

**Comment by l00mi** [comment]
Do you see the same behaviour with Image > Convert to Grey > Cubic Spline ?
