### ISSUE TITLE
floating point slider bar updates

### ISSUE THREAD

**Issue by ladotonia** [cpvrlab/ImagePlay#78]
When dragging a slider bar in the settings of a process, changes can be ignored while the previous thread is being processed.  When the previous thread completes, the process is not ready, but the grid has been updated to _updateNeeded false.

This can be replicated by creating a long chain of processes with a split planes process and dragging the hue shift slider bar.  When completed the image won't match the last setting.  Also since the process is not ready, it will prevent the user from switching between output images (r/g/b) in the combo box in the image viewer.

**Comment by schmk2** [comment]
Thanks for the pull request. Unfortunately it does not fix the issue entirely. I merged your code nevertheless, because it improves the behavior sometimes.

You can replicate the issue for example with a large image and a large gaussian filter. The result sometimes does not reflect the latest parameters.

We are aware of the issue but a solution is not easily implemented. Maybe we need to change our graph-traversing logic. If you have a great idea on how to fix it, we are open for suggestions.

**Comment by ladotonia** [comment]
This is a duplicate of an open bug #2, closing this one
