### ISSUE TITLE
ImagePlay not working on jetson tk1 board

### ISSUE THREAD

**Issue by ParonoidAndroid** [cpvrlab/ImagePlay#90]
Hello! I am using the jetson tk1 to do image analysis and I have encountered an issue where upon installing I see an error pop up at the bottom of the program. I am wondering if this is related to my board or if there is something else that is wrong...

http://imgur.com/6ZEOB8y

I also noticed that the only images accepted are ImagePlay json files... I am unable to import image files for whatever reason.

http://i.imgur.com/HyE8xxs.png

The jetson tk1

 http://elinux.org/Jetson_TK1

Hope to hear from you soon!

**Comment by schmk2** [comment]
The error happens because of an issue with file paths under linux. Please disable the "autosave" feature for now:
![2016-02-02 12_45_47-settings](https://cloud.githubusercontent.com/assets/11331299/12748542/4993e84c-c9ab-11e5-87db-959ceb58305f.png)

In order to load an image file, drag and drop the process "Load Image" to the working area.
![2016-02-02 12_49_27-imageplay](https://cloud.githubusercontent.com/assets/11331299/12748576/78f6b740-c9ab-11e5-9916-1844b9b4f320.png)

It supports *.bmp, *.gif, *.hdr, *.jpg, *.png, *.psd, *.tiff, *.cr2 and many more...

The tutorial is available in the [?] menu.
